theme: jekyll-theme-cayman
include: 
 - css-and-scss/css-and-sass-styleguide.md
 - java-coding-guide-lines/index.md
 - java-coding-guide-lines/java-guidelines-from-sonarcube.md
 - javascript/coding-convensions/comparison-operators-and-equality.md
 - javascript/coding-convensions/es-modules.md
 - javascript/coding-convensions/naming-convensions.md
 - javascript/coding-convensions/index.md
 - javascript/coding-convensions/variable-naming-convensions.md
 - javascript/es6-and-above/arrow-functions.md
 - javascript/es6-and-above/classes-and-inheritance.md
 - javascript/es6-and-above/default-parameters.md
 - javascript/es6-and-above/destructuring.md
 - javascript/es6-and-above/object-shorthand.md
 - javascript/es6-and-above/rest-operator.md
 - javascript/es6-and-above/spread-operator.md
 - javascript/es6-and-above/template-strings.md
 - javascript/es6-and-above/object-computed.md
 - javascript/react-jsx-style-guide/index.md
 - javascript/react-jsx-style-guide/style-guide.md
 - javascript/source-file-basics.md
 - javascript/special-characters.md 

 docgroups:
  - title: Java Coding Guidelines
    subfolderitems:
      - page: Guidelines Overview
        url: /java-coding-guide-lines/index.html
        subsubfolderitems:
          - page: Sonarcube GuideLines
            url: /java-coding-guide-lines/java-guidelines-from-sonarcube.html
  - title: Group 2
    subfolderitems:
      - page: Piece 1
        url: /piece1.html
      - page: Piece 2
        url: /piece2.html
      - page: Piece 3
        url: /piece3.html
        subsubfolderitems:
          - page: Subpiece 1
            url: /subpiece1.html
          - page: Subpiece2
            url: /subpiece2.html
  - title: Group 3
    subfolderitems:
      - page: Widget 1
        url: /widget1.html
        subsubfolderitems:
          - page: Subwidget 1
            url: /subwidget1.html
          - page: Subwidget 2
            url: /subwidget2.html
      - page: Widget 2
        url: /widget2.html
      - page: Widget 3
        url: /widget3.html